/****************************************************************************
* 文件名：CONFIG.H
* 功能：配置文件，用于方便项目管理。
* 说明：所有项目C程序文件包含此头文件即可。
****************************************************************************/
#ifndef  CONFIG_H
  #define	 CONFIG_H

/* 包含头文件 */
	#include "sys.h"
	#include "usart.h"		
	#include "delay.h"	
	#include "pwm.h"
	#include "exti.h"
	#include "timer.h"
	#include "sg.h"
	#include "function.h"

#endif
